# LINUX_OVERRIDE_SRCDIR = $(BR2_EXTERNAL)/../linux
# LIBMGURDY_OVERRIDE_SRCDIR = $(BR2_EXTERNAL)/../mg-core/mgurdy-lib
# PYTHON_MGURDY_OVERRIDE_SRCDIR = $(BR2_EXTERNAL)/../mg-core/mgurdy
# FLUIDSYNTH_OVERRIDE_SRCDIR = $(BR2_EXTERNAL)/../fluidsynth
# MGWEB_OVERRIDE_SRCDIR = $(BR2_EXTERNAL)/../mg-web
# MGEFFECTS_OVERRIDE_SRCDIR = $(BR2_EXTERNAL)/../mg-effects
# MGDOCS_OVERRIDE_SRCDIR = $(BR2_EXTERNAL)/../mg-docs
