#!/bin/sh

#
# Remaining MidiGurdy setup tasks that can safely be
# done after main program start
#

case "$1" in
    start)
        # make sure we see segfaults in syslog.
        # FIXME: this should really be set via kernel command line
        echo 1 > /proc/sys/kernel/print-fatal-signals

        # Set IRQ and thread priorities
        /usr/bin/mgprio.sh

        # Restore ALSA configuration
        /usr/sbin/alsactl -f /etc/asound.state restore

        # Load sysctl values
        sysctl -p

        # Set the I2C IRQ and thread affinity to CPU 1,
        # otherwise me might get a stuck I2C bus on shutdown,
        # resulting in incomplete poweroff of AXP209
        /usr/bin/i2cprio.sh
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

