#!/bin/sh

case "$1" in
    start)
        printf "Starting sysinfo server\n"
        /usr/bin/python /usr/bin/mgsysinfo.py &> /dev/null &
        printf "Starting crashdump handler\n"
        /usr/bin/mgcrashdump &> /dev/null &
        ;;
    stop)
        killall -q mgcrashdump
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?
