#!/bin/sh
#
# Load USB networking module
#

case "$1" in
    start)
        echo "Configuring USB gadget"
        /usr/bin/mgusb_gadget.sh start

        # make sure mgurdy core knows current usb configuration
        /usr/bin/mdev_extcon.sh

        echo "Configuring USB networking"
        /usr/bin/mgusb_network.sh start

        echo "Loading USB audio support"
        modprobe snd_usb_audio
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
